sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t olavokruel/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true olavokruel/react-test npm run test

after_success:
  - docker build -t olavokruel/multi-client ./client
  - docker build -t olavokruel/multi-server ./server
  - docker build -t olavokruel/multi-worker ./worker
  - docker build -t olavokruel/multi-nginx ./nginx
#Log in to Docker CLI with environment variables in TRAVIS
  - docker login -u "DOCKER_ID" -p "DOCKER_PASSWORD" docker.io
  # - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin docker.io
#Push the built images into Docker Hub
  - docker push olavokruel/multi-client:olavokruel/multi-client
  - docker push olavokruel/multi-server:olavokruel/multi-client
  - docker push olavokruel/multi-worker:olavokruel/multi-client
  - docker push olavokruel/multi-nginx:olavokruel/multi-client