sudo: required
services:
  - docker

before_install:
  - docker build -t olavokruel/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true olavokruel/react-test npm run test

after_success:
  - docker build -t olavokruel/multi-client ./client
  - docker build -t olavokruel/multi-nginx ./nginx
  - docker build -t olavokruel/multi-server ./server
  - docker build -t olavokruel/multi-worker ./worker
# Log in to Docker CLI with environment variables in TRAVIS
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push the built images into Docker Hub - Changed a few things
  - docker push olavokruel/multi-client
  - docker push olavokruel/multi-nginx
  - docker push olavokruel/multi-server
  - docker push olavokruel/multi-worker

deploy:
  # edge: true
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-507590172939
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY