sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t olavokruel/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true olavokruel/react-test npm run test

after_success:
  - docker build -t olavokruel/multi-client ./client
  - docker build -t olavokruel/multi-server ./server
  - docker build -t olavokruel/multi-worker ./worker
  - docker build -t olavokruel/multi-nginx ./nginx
#Log in to Docker CLI with environment variables in TRAVIS
#Had to reconnect my github to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
#Push the built images into Docker Hub
  - docker push olavokruel/multi-client
  - docker push olavokruel/multi-server
  - docker push olavokruel/multi-worker
  - docker push olavokruel/multi-nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "sa-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-sa-east-1-507590172939"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY